In [15]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [2]:
reviews = ['nice food',
          'amazing ambience',
          'excellent food',
          'will go again',
          'simply loved it!',
          'horrible food',
          'never go there, bad food',
          'poor service',
          'poor quality',
          'needs improvement']
sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [5]:
one_hot('amazing restaurant',25)

[5, 6]

In [6]:
vocab_size = 25
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[16, 17],
 [5, 13],
 [20, 17],
 [3, 16, 12],
 [20, 7, 3],
 [5, 17],
 [19, 16, 3, 22, 17],
 [7, 13],
 [7, 13],
 [23, 21]]

# Padding for the neural network

In [13]:
max_length = max([len(rev.split(' ')) for rev in reviews])
max_length

5

In [16]:
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
padded_reviews

array([[16, 17,  0,  0,  0],
       [ 5, 13,  0,  0,  0],
       [20, 17,  0,  0,  0],
       [ 3, 16, 12,  0,  0],
       [20,  7,  3,  0,  0],
       [ 5, 17,  0,  0,  0],
       [19, 16,  3, 22, 17],
       [ 7, 13,  0,  0,  0],
       [ 7, 13,  0,  0,  0],
       [23, 21,  0,  0,  0]])

In [22]:
embeded_vector_size = 5
model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name='embedding'))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [18]:
x = padded_reviews
y = sentiment

In [26]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 5, 5)              125       
                                                                 
 flatten_2 (Flatten)         (None, 25)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 26        
                                                                 
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [27]:
model.fit(x,y, epochs=50, verbose=0)

In [28]:
loss, accuracy = model.evaluate(x,y)
accuracy

1/1 [==============================] - 2s 2s/step - loss: 0.6578 - accuracy: 0.8000


0.800000011920929

In [29]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

25

# Nice is encoded as 16 and excellent as 20, so let's see if their vectors are similar

In [30]:
weights[16]

array([ 0.00681603,  0.08987749, -0.01481276,  0.01737909,  0.06535628],
      dtype=float32)

In [31]:
weights[20]

array([0.05188414, 0.05488469, 0.00936513, 0.06292278, 0.02848459],
      dtype=float32)